/** Camera and input constants. UI layout lives in `viewConfig.ts`. */
export const CAMERA_CONFIG = {
  startPolarDeg: 55,
  startAzimuthDeg: 0,
  polarMinDeg: 10,
  polarMaxDeg: 170,
  startDistanceBase: Math.hypot(75, 95),
  startDistanceAspect: 1.2,
  systemZoomMaxFactor: 1.5,
  systemZoomMinFactor: 0.2,
  bodyZoomMinRadiusFactor: 2.5,
  zoomStepIn: 0.9,
  zoomStepOut: 1.1,
  wheelNotchDeltaPx: 100,
  wheelNotchMinDeltaPx: 50,
  wheelGestureGapMs: 150,
  pinchDeltaPerStep: 10,
  dampingFactor: 0.08,
  dampingReferenceFps: 60,
  tapMaxMovePx: 6,
  tapMaxDurationMs: 300,
  hitRadiusMousePx: 24,
  hitRadiusTouchPx: 44,
  keyRotateStepDeg: 5,
  keyRotateStepShiftDeg: 15,
  flightToBodySeconds: 1.2,
  flightToSystemSeconds: 1.0,
  bodyDistanceRadiusFactor: 6,
  sunDistanceRadiusFactor: 3.5,
  reducedMotionFadeMs: 150,
  orbitOpacitySelected: 0.8,
  orbitOpacityDimmed: 0.35,
} as const;
